spring:
  jackson:
    default-property-inclusion: custom
  config:
    import: file:env.properties
  application:
    name: Rewerk Webstore
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 500
jwt:
  issuer: ${JWT_ISSUER}
  lifetime: 7
  sign: ${JWT_SIGN}
uploads:
  project_id: ${GCS_PROJECT_ID}
  product_images_bucket_name: ${GCS_PRODUCT_IMAGES_BUCKET_NAME}
  brand_images_bucket_name: ${GCS_BRAND_IMAGES_BUCKET_NAME}
  review_images_bucket_name: ${GCS_REVIEW_IMAGES_BUCKET_NAME}
